Repository room-number7-presents/issue-tracker-max, pull requests merged in 2023-07, with the labels that each got.

#2 [BE] 프로젝트 기본 설정 (#1)
  .gitignore
  README.md
  be/issue-tracker/.gitignore
  be/issue-tracker/build.gradle
  be/issue-tracker/gradle/wrapper/gradle-wrapper.jar
  be/issue-tracker/gradle/wrapper/gradle-wrapper.properties
  be/issue-tracker/gradlew
  be/issue-tracker/gradlew.bat
  be/issue-tracker/settings.gradle
  be/issue-tracker/src/main/java/org/presents/issuetracker/IssueTrackerApplication.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/controller/CommentController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/request/CommentRequestDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/response/CommentResponseDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/entity/Comment.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/repository/CommentRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/service/CommentService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/controller/IssueController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/request/IssueRequestDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/response/IssueResponseDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/Issue.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/repository/IssueRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/service/IssueService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelRequestDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/response/LabelResponseDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/Label.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/controller/MilestoneController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/request/MilestoneRequestDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/response/MilestoneResponseDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/entity/Milestone.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/repository/MilestoneRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/service/MilestoneService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/controller/UserController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/dto/request/UserRequestDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/dto/response/UserResponseDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/entity/User.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/repository/UserRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/service/UserService.java
  be/issue-tracker/src/main/resources/application-prodDB.yml
  be/issue-tracker/src/main/resources/application.yml
  be/issue-tracker/src/main/resources/schema.sql
  be/issue-tracker/src/test/java/org/presents/issuetracker/IssueTrackerApplicationTests.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/annotation/ControllerTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/annotation/RepositoryTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/annotation/ServiceTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/comment/CommentControllerTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/comment/CommentRepositoryTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/comment/CommentServiceTest.java
  be/issue-tracker/src/test/resources/data.sql
  be/issue-tracker/src/test/resources/schema.sql
Labels: BE, setting

#8 [FE] Button 컴포넌트 구현
  fe/src/components/common/Button.tsx
Labels: FE, feat

#9 [BE] fix: schema.sql 수정 (#1)
  be/issue-tracker/src/main/resources/schema.sql
Labels: BE, fix

#12 [FE] Dropdown 컴포넌트 구현 (#4)
  fe/src/assets/icons/userImageSmall.svg
  fe/src/components/common/dropDown/DropDownContainer.tsx
  fe/src/components/common/dropDown/DropDownIndicator.tsx
  fe/src/components/common/dropDown/DropDownList.tsx
  fe/src/components/common/dropDown/DropDownPanel.tsx
  fe/src/components/common/dropDown/types.ts
  fe/src/pages/IssueListPage.tsx
Labels: FE, feat
