Repository room-number7-presents/issue-tracker-max, pull requests merged in 2023-08, with the labels that each got.

#17 [FE] TextArea 컴포넌트 구현 (#13)
  fe/src/assets/icons/grip.svg
  fe/src/components/common/TextArea.tsx
  fe/src/pages/AddIssuePage.tsx
  fe/src/pages/IssueListPage.tsx
  fe/src/styles/designSystem.ts
  fe/src/styles/globalStyle.ts
Labels: FE, feat

#14 [FE] TextInput 컴포넌트 구현 (#7)
  fe/src/components/common/TextInput.tsx
Labels: FE, feat

#20 [FE] Color Code Input 컴포넌트 구현 #15
  fe/src/components/common/TextInput.tsx
Labels: FE, feat

#23 [FE] InformationTag 컴포넌트 구현 (#19)
  fe/src/components/common/InformationTag.tsx
Labels: FE, feat

#25 [FE] FilterBar 컴포넌트 구현 (#21)
  fe/src/components/common/ColorCodeInput.tsx
  fe/src/components/common/FilterBar.tsx
  fe/src/components/common/TextInput.tsx
  fe/src/components/common/TextInput/Input.tsx
  fe/src/components/common/TextInput/InputContainer.tsx
Labels: FE, feat

#28 [FE] ProgressBar 컴포넌트 구현 (#24)
  fe/src/components/common/ProgressBar.tsx
  fe/src/components/common/ProgressLabel.tsx
Labels: FE, feat

#31 [FE] Dropdown 컴포넌트 분리 (#29)
  fe/src/components/common/dropDown/DropDownContainer.tsx
  fe/src/components/common/dropDown/DropDownHeader.tsx
  fe/src/components/common/dropDown/DropDownIndicator.tsx
  fe/src/components/common/dropDown/DropDownList.tsx
  fe/src/components/common/dropDown/DropDownPanel.tsx
Labels: FE, feat

#34 feat: Label 생성 API 구현 (#11)
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelRequestDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/Label.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
Labels: BE, feat

#35 [BE] Label 수정 API 구현 (#22)
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/Label.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
Labels: BE, feat

#18 [BE] mybatis 설정 적용
  be/issue-tracker/build.gradle
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/controller/IssueController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/IssueDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/mapper/IssueMapper.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/service/IssueService.java
  be/issue-tracker/src/main/resources/application.yml
  be/issue-tracker/src/main/resources/mybatis/mapper/IssueMapper.xml
  be/issue-tracker/src/main/resources/mybatis/mybatis-config.xml
  be/issue-tracker/src/main/resources/schema.sql
Labels: BE, feat

#33 [BE] 이슈 생성 기능 구현
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/dto/response/IdResponseDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/controller/IssueController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/request/IssueCreateRequestDto.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/Assignee.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/Issue.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/IssueLabel.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/repository/IssueRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/service/IssueService.java
Labels: BE, feat

#45 [FE] TabButton 컴포넌트 구현 (#27)
  fe/src/components/common/Button.tsx
  fe/src/components/common/ColorCodeInput.tsx
  fe/src/components/common/FilterBar.tsx
  fe/src/components/common/TextInput/TextInput.tsx
  fe/src/components/common/tabButton/Tab.tsx
  fe/src/components/common/tabButton/TabButton.tsx
  fe/src/components/common/tabButton/TabContainer.tsx
Labels: FE, feat

#37 [BE] CI/CD 환경 구축
  .github/workflows/deploy-be.yml
  .github/workflows/deploy-fe.yml
  be/issue-tracker/appspec.yml
  be/issue-tracker/build.gradle
  be/issue-tracker/scripts/deploy.sh
  be/issue-tracker/src/main/resources/application-prodDB.yml
  be/issue-tracker/src/main/resources/application.yml
  be/issue-tracker/src/main/resources/schema.sql
  be/issue-tracker/src/test/resources/schema.sql
Labels: BE, FE, chore

#47 [FE] SideBar 컴포넌트 구현 (#32)
  fe/src/components/common/InformationTag.tsx
  fe/src/components/common/dropDown/DropDownIndicator.tsx
  fe/src/components/common/dropDown/DropDownList.tsx
  fe/src/components/common/dropDown/types.ts
  fe/src/components/common/sideBar/ListAssignee.tsx
  fe/src/components/common/sideBar/ListLabel.tsx
  fe/src/components/common/sideBar/ListMilestone.tsx
  fe/src/components/common/sideBar/ListSideBar.tsx
  fe/src/components/common/sideBar/SideBar.tsx
  fe/src/pages/AddIssuePage.tsx
  fe/src/pages/IssueListPage.tsx
Labels: FE, feat

#51 feat: Label 수정 API 구현 (#22)
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/dto/response/LabelResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelCreateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelUpdateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/response/LabelResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/Label.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
Labels: BE, feat

#53 [BE] Label 선택용 목록 조회 API 구현
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelCreateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelUpdateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/response/LabelPreviewResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/response/LabelResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/Label.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
Labels: BE, feat

#55 [BE] Label 삭제 조회 API 구현
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
Labels: BE, feat

#61 [FE] AddIssuePage (#50)
  fe/src/App.tsx
  fe/src/components/addIssuePage/Body.tsx
  fe/src/components/addIssuePage/ButtonContainer.tsx
  fe/src/components/addIssuePage/ContentInput.tsx
  fe/src/components/addIssuePage/InputContainer.tsx
  fe/src/components/addIssuePage/SideBar.tsx
  fe/src/components/addIssuePage/Title.tsx
  fe/src/components/addIssuePage/TitleInput.tsx
  fe/src/components/addIssuePage/UserImage.tsx
  fe/src/components/addIssuePage/UserImageContainer.tsx
  fe/src/components/common/TextArea.tsx
  fe/src/components/common/TextInput/InputContainer.tsx
  fe/src/components/common/dropDown/DropDownIndicator.tsx
  fe/src/components/common/dropDown/DropDownList.tsx
  fe/src/components/common/dropDown/DropDownPanel.tsx
  fe/src/components/common/sideBar/ListAssignee.tsx
  fe/src/components/common/sideBar/ListLabel.tsx
  fe/src/components/common/sideBar/ListMilestone.tsx
  fe/src/components/common/sideBar/ListSideBar.tsx
  fe/src/components/common/sideBar/SideBar.tsx
  fe/src/pages/AddIssuePage.tsx
  fe/src/pages/NotFoundPage.tsx
  fe/src/routes.tsx
Labels: FE, feat

#64 Fe/feature/#50
  fe/src/App.tsx
  fe/src/components/addIssuePage/Body.tsx
  fe/src/components/addIssuePage/ButtonContainer.tsx
  fe/src/components/addIssuePage/ContentInput.tsx
  fe/src/components/addIssuePage/InputContainer.tsx
  fe/src/components/addIssuePage/SideBar.tsx
  fe/src/components/addIssuePage/Title.tsx
  fe/src/components/addIssuePage/TitleInput.tsx
  fe/src/components/addIssuePage/UserImage.tsx
  fe/src/components/addIssuePage/UserImageContainer.tsx
  fe/src/components/common/TextArea.tsx
  fe/src/components/common/TextInput/InputContainer.tsx
  fe/src/components/common/dropDown/DropDownIndicator.tsx
  fe/src/components/common/dropDown/DropDownList.tsx
  fe/src/components/common/dropDown/DropDownPanel.tsx
  fe/src/components/common/sideBar/ListAssignee.tsx
  fe/src/components/common/sideBar/ListLabel.tsx
  fe/src/components/common/sideBar/ListMilestone.tsx
  fe/src/components/common/sideBar/ListSideBar.tsx
  fe/src/components/common/sideBar/SideBar.tsx
  fe/src/pages/AddIssuePage.tsx
  fe/src/pages/NotFoundPage.tsx
  fe/src/routes.tsx
Labels: FE, feat

#66 [FE] IssueListPage 기능 중간 머지 (#49)
  fe/src/assets/icons/base-profile-image.jpeg
  fe/src/components/common/FilterBar.tsx
  fe/src/components/common/box/Box.tsx
  fe/src/components/common/textInput/Input.tsx
  fe/src/components/common/textInput/InputContainer.tsx
  fe/src/components/common/textInput/TextInput.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/issueListPage/IssueList.tsx
  fe/src/components/issueListPage/IssueTable.tsx
  fe/src/components/issueListPage/SubNav.tsx
  fe/src/components/issueListPage/TableHeader.tsx
  fe/src/pages/IssueListPage.tsx
  fe/src/routes.tsx
Labels: FE, feat

#75 [FE] textarea컴포넌트 분리, comment컴포넌트 ui 구현 (#50refactor)
  fe/src/App.tsx
  fe/src/assets/icons/userImageLarge.svg
  fe/src/assets/icons/userImageSmall.svg
  fe/src/components/addIssuePage/Body.tsx
  fe/src/components/addIssuePage/ButtonContainer.tsx
  fe/src/components/addIssuePage/Title.tsx
  fe/src/components/common/TextArea.tsx
  fe/src/components/common/box/Box.tsx
  fe/src/components/common/comment/CommentHeader.tsx
  fe/src/components/common/comment/Commentt.tsx
  fe/src/components/common/dropDown/DropDownIndicator.tsx
  fe/src/components/common/dropDown/DropDownList.tsx
  fe/src/components/common/dropDown/DropDownPanel.tsx
  fe/src/components/common/sideBar/ListAssignee.tsx
  fe/src/components/common/sideBar/ListSideBar.tsx
  fe/src/components/common/sideBar/SideBar.tsx
  fe/src/components/common/textArea/AddButtons.tsx
  fe/src/components/common/textArea/Caption.tsx
  fe/src/components/common/textArea/ErrorMessages.tsx
  fe/src/components/common/textArea/TextArea.tsx
  fe/src/components/common/textArea/TextAreaContainer.tsx
  fe/src/components/common/textArea/TextAreaInput.tsx
  fe/src/components/issueDetailPage/Comment.tsx
  fe/src/components/issueListPage/IssueTable.tsx
  fe/src/components/labelListPage/AddLabelTable.tsx
  fe/src/components/labelListPage/Body.tsx
  fe/src/components/labelListPage/EditLabel.tsx
  fe/src/components/labelListPage/InitialLabelTable.tsx
  fe/src/components/labelListPage/SubNav.tsx
  fe/src/components/signPage/SignForm.tsx
  fe/src/mocks/data/selectList.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/AddIssuePage.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/pages/IssueListPage.tsx
  fe/src/pages/LabelListPage.tsx
  fe/src/pages/MileStoneListPage.tsx
  fe/src/pages/SignPage.tsx
  fe/src/routes.tsx
  fe/src/utils/api.ts
Labels: FE, feat

#73 [BE] 이슈 생성 및 상세조회 리팩토링
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/request/CommentRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/response/CommentResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/entity/Comment.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/entity/vo/CommentWithAuthor.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/controller/IssueController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/request/IssueCreateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/response/IssueDetailResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/vo/IssueDetailInfo.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/mapper/IssueMapper.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/repository/IssueRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/service/IssueService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/response/LabelPreviewResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/response/LabelResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/Label.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/vo/LabelVo.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/request/MilestoneRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/response/MilestonePreviewResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/response/MilestoneResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/entity/vo/MilestoneInfo.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/entity/vo/MilestonePreview.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/dto/request/UserRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/dto/response/UserResponse.java
  be/issue-tracker/src/main/resources/mybatis/mapper/IssueMapper.xml
  be/issue-tracker/src/test/java/org/presents/issuetracker/issue/IssueControllerTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/issue/IssueMapperTest.java
Labels: refactor, BE

#74 [BE] Label API 리팩터링
  be/issue-tracker/build.gradle
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/dto/response/LabelIdResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/dto/response/LabelResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelCreateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/request/LabelUpdateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/dto/response/LabelPreviewResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/Label.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
Labels: refactor, BE

#76 [BE] 이슈 목록 반환 API 오류 해결 및 리팩토링
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/controller/IssueController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/request/IssueSearchParam.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/response/IssueSearch.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/response/IssueSearchResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/response/LabelSearch.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/response/UserSearch.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/AssigneeImage.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/vo/IssueSearchCountInfo.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/entity/vo/IssueSearchInfo.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/mapper/IssueMapper.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/service/IssueService.java
  be/issue-tracker/src/main/resources/mybatis/mapper/IssueMapper.xml
Labels: refactor, BE, fix

#80 [FE] fe 자동배포
  .github/workflows/deploy-fe.yml
  fe/src/utils/api.ts
Labels: FE

#88 [FE] 레이블, 마일스톤 페이지 UI 구현 #86
  fe/src/components/common/ProgressLabel.tsx
  fe/src/components/common/Table/TableBody.tsx
  fe/src/components/common/Table/TableContainer.tsx
  fe/src/components/common/Table/TableHeader.tsx
  fe/src/components/common/dropDown/DropDownContainer.tsx
  fe/src/components/common/dropDown/DropDownIndicator.tsx
  fe/src/components/common/dropDown/types.ts
  fe/src/components/labelListPage/AddLabelTable.tsx
  fe/src/components/labelListPage/Body.tsx
  fe/src/components/labelListPage/EditLabel.tsx
  fe/src/components/labelListPage/InitialLabelTable.tsx
  fe/src/components/labelListPage/LabelItem.tsx
  fe/src/components/labelListPage/SubNav.tsx
  fe/src/components/milestoneListPage/AddMileStoneTable.tsx
  fe/src/components/milestoneListPage/Body.tsx
  fe/src/components/milestoneListPage/EditMileStone.tsx
  fe/src/components/milestoneListPage/InitialMileStoneTable.tsx
  fe/src/components/milestoneListPage/MilestoneItem.tsx
  fe/src/components/milestoneListPage/SubNav.tsx
  fe/src/pages/LabelListPage.tsx
  fe/src/pages/MileStoneListPage.tsx
  fe/src/routes.tsx
  fe/src/types/custom.d.ts
Labels: FE, feat

#94 [BE] fix: loginId를 userId로 수정 (#90)
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/response/AssigneeSearch.java
  be/issue-tracker/src/main/resources/mybatis/mapper/IssueMapper.xml
Labels: BE, fix

#87 [BE] 글로벌 예외 처리를 위한 기능 구현 (#82)
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/exception/CustomException.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/handler/GlobalExceptionHandler.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/response/CommonApiResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/ErrorCode.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/StatusCode.java
  be/issue-tracker/src/main/resources/application.yml
  be/issue-tracker/src/test/java/org/presents/issuetracker/exception/ExceptionTest.java
Labels: BE, feat

#85 [FE] feat: IssueDetail 페이지 UI구현 (#81)
  fe/src/components/common/comment/Commentt.tsx
  fe/src/components/common/textArea/TextAreaInput.tsx
  fe/src/components/issueDetailPage/AddNewComment.tsx
  fe/src/components/issueDetailPage/Body.tsx
  fe/src/components/issueDetailPage/CommentContainer.tsx
  fe/src/components/issueDetailPage/CommentInput.tsx
  fe/src/components/issueDetailPage/PostInformation.tsx
  fe/src/components/issueDetailPage/PostInformationHeaderMeta.tsx
  fe/src/components/issueDetailPage/SideBarRightPanel.tsx
  fe/src/pages/AddIssuePage.tsx
  fe/src/pages/IssueDetailPage.tsx
  fe/src/utils/api.ts
Labels: FE, feat

#100 [BE] 파일 업로드 기능 구현 + 마일스톤, 사용자 선택용 목록 조회
  .github/workflows/deploy-be.yml
  .github/workflows/deploy-fe.yml
  be/issue-tracker/.gitignore
  be/issue-tracker/build.gradle
  be/issue-tracker/src/main/java/org/presents/issuetracker/IssueTrackerApplication.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/file/FileUploadController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/config/S3Config.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/FileErrorCode.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/IssueErrorCode.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/controller/IssueController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/request/IssueCreateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/service/IssueService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/controller/MilestoneController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/response/MilestonePreviewResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/repository/MilestoneRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/service/MilestoneService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/controller/UserController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/dto/response/UserResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/repository/UserRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/service/UserService.java
  be/issue-tracker/src/main/resources/application.yml
  be/issue-tracker/src/test/java/org/presents/issuetracker/issue/IssueControllerTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/milestone/MilestoneRepositoryTest.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/user/UserRepositoryTest.java
Labels: BE, feat

#102 [FE] IssueListPage 기능 구현 (#49)
  fe/src/assets/icons/basic-profile.jpeg
  fe/src/assets/icons/checkBoxActive.svg
  fe/src/assets/icons/checkBoxDisable.svg
  fe/src/components/common/FilterBar.tsx
  fe/src/components/common/box/Box.tsx
  fe/src/components/common/box/BoxHeader.tsx
  fe/src/components/common/dropDown/DropDownContainer.tsx
  fe/src/components/common/dropDown/DropDownList.tsx
  fe/src/components/common/dropDown/DropDownPanel.tsx
  fe/src/components/header/Header.tsx
  fe/src/components/issueListPage/IssueList.tsx
  fe/src/components/issueListPage/IssueTable.tsx
  fe/src/components/issueListPage/ResetFilterButton.tsx
  fe/src/components/issueListPage/SubNav.tsx
  fe/src/components/issueListPage/TableHeader.tsx
  fe/src/mocks/data/issues.ts
  fe/src/mocks/handlers.ts
  fe/src/pages/IssueListPage.tsx
  fe/src/routes.tsx
  fe/src/types/custom.d.ts
  fe/src/utils/generateEncodedQuery.ts
  fe/src/utils/localStorage.ts
  fe/src/utils/processFilterString.ts
  fe/src/utils/time.ts
Labels: FE, feat

#110 [BE] feat: 이슈 목록 조회 시 filter에 "OO없는 이슈" 추가
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/dto/request/IssueSearchParam.java
  be/issue-tracker/src/main/resources/mybatis/mapper/IssueMapper.xml
Labels: BE, feat, fix

#112 [BE] fix: 로그 레벨 변경
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/handler/GlobalExceptionHandler.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/ErrorCode.java
Labels: BE, fix

#116 [BE] 회원가입 기능 구현
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/UserErrorCode.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/issue/service/IssueService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/controller/UserController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/dto/request/UserRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/repository/UserRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/service/UserService.java
  be/issue-tracker/src/main/resources/schema.sql
Labels: BE, feat

#118 [FE] Alert 컴포넌트 구현 (#115)
  fe/src/components/common/Alert.tsx
Labels: FE, feat

#122 [FE] label 상세 페이지 삭제 모달 기능 구현 (#120)
  fe/src/apis/api.ts
  fe/src/components/labelListPage/Body.tsx
  fe/src/components/labelListPage/LabelEditBody.tsx
  fe/src/components/labelListPage/LabelItem.tsx
  fe/src/pages/LabelListPage.tsx
Labels: refactor, FE, feat

#123 [BE] Comment 생성, 수정, 삭제 API 구현
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/controller/CommentController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/request/CommentCreateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/request/CommentRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/response/CommentResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/dto/response/CommentUpdateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/entity/Comment.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/repository/CommentRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/comment/service/CommentService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/dto/response/IdResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/dto/response/LabelIdResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/CommentErrorCode.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/entity/User.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/repository/UserRepository.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/comment/CommentRepositoryTest.java
Labels: BE, feat

#127 [BE] feat: oauth 로그인 및 회원가입 완료
  .github/workflows/deploy-be.yml
  be/issue-tracker/.gitignore
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/OauthErrorCode.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/filter/JwtAuthorizationFilter.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/oauth/controller/OauthController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/oauth/entity/GithubUser.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/oauth/service/OauthService.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/entity/User.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/user/repository/UserRepository.java
  be/issue-tracker/src/main/resources/schema.sql
Labels: BE, feat

#128 [BE] fix: 커스텀 에러로 변경 (close #96)
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/error/statuscode/OauthErrorCode.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/oauth/service/OauthService.java
Labels: BE, fix

#131 [BE] fix: Oauth 회원가입 시, loginId postfix 변경 (#96)
  be/issue-tracker/src/main/java/org/presents/issuetracker/oauth/entity/GithubUser.java
Labels: BE, fix

#130 [FE] 로그인, 회원가입 기능 구현
  fe/src/apis/api.ts
  fe/src/components/header/Header.tsx
  fe/src/components/signPage/LoginForm.tsx
  fe/src/components/signPage/RegisterForm.tsx
  fe/src/components/signPage/validateInput.ts
  fe/src/constants/PATH.ts
  fe/src/pages/AddIssuePage.tsx
  fe/src/pages/IssueListPage.tsx
  fe/src/pages/NotFoundPage.tsx
  fe/src/pages/RegisterPage.tsx
  fe/src/pages/SignPage.tsx
  fe/src/routes.tsx
Labels: FE, feat

#132 [BE] Milestone API 구현
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/controller/MilestoneController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/request/MilestoneRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/request/MilestoneStatusUpdateRequest.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/dto/response/MilestoneResponse.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/entity/Milestone.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/entity/vo/MilestoneInfo.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/repository/MilestoneRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/milestone/service/MilestoneService.java
Labels: BE, feat

#134 [BE] Label 상세 조회 응답에 레이블, 마일스톤 개수 추가
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/controller/LabelController.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/entity/vo/LabelInfo.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/repository/LabelRepository.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/label/service/LabelService.java
Labels: BE, feat

#135 [BE] fix: OAuth 로그인 시, 프론트에서 github에 직접 접근하도록 수정 (#96)
  be/issue-tracker/src/main/java/org/presents/issuetracker/oauth/controller/OauthController.java
Labels: BE, fix

#151 [BE] test: 이슈 목록 반환 Controller 테스트 (#83)
  be/issue-tracker/src/test/java/org/presents/issuetracker/issue/IssueControllerTest.java
Labels: BE, test

#150 [BE] Response cors 필터 적용
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/config/FilterConfig.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/filter/CorsFilter.java
Labels: BE, fix

#152 [BE] IssueControllerTest 반영 (#83)
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/config/FilterConfig.java
  be/issue-tracker/src/main/java/org/presents/issuetracker/global/filter/CorsFilter.java
  be/issue-tracker/src/test/java/org/presents/issuetracker/issue/IssueControllerTest.java
Labels: BE, test
